use super::types::{AgentConfig, AgentKind, AgentTrigger};

fn audit_agent(command: &str) -> AgentConfig {
    AgentConfig {
        kind: AgentKind::Audit,
        name: String::new(),
        enabled: true,
        command: command.into(),
        trigger: AgentTrigger::Manual,
        timeout_secs: 120,
        working_dir: String::new(),
        before_run: String::new(),
    }
}

// ---------------------------------------------------------------------------
// Language presets for agent initialization
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum AgentLanguage {
    Rust,
    TypeScript,
    Python,
    Go,
    Java,
    CSharp,
    Ruby,
    Swift,
    Kotlin,
    Cpp,
    Elixir,
    Zig,
    Lua,
}

impl AgentLanguage {
    pub fn label(&self) -> &'static str {
        match self {
            AgentLanguage::Rust => "Rust",
            AgentLanguage::TypeScript => "TypeScript",
            AgentLanguage::Python => "Python",
            AgentLanguage::Go => "Go",
            AgentLanguage::Java => "Java",
            AgentLanguage::CSharp => "C#",
            AgentLanguage::Ruby => "Ruby",
            AgentLanguage::Swift => "Swift",
            AgentLanguage::Kotlin => "Kotlin",
            AgentLanguage::Cpp => "C/C++",
            AgentLanguage::Elixir => "Elixir",
            AgentLanguage::Zig => "Zig",
            AgentLanguage::Lua => "Lua",
        }
    }

    pub fn all() -> &'static [AgentLanguage] {
        &[
            AgentLanguage::Rust,
            AgentLanguage::TypeScript,
            AgentLanguage::Python,
            AgentLanguage::Go,
            AgentLanguage::Java,
            AgentLanguage::CSharp,
            AgentLanguage::Ruby,
            AgentLanguage::Swift,
            AgentLanguage::Kotlin,
            AgentLanguage::Cpp,
            AgentLanguage::Elixir,
            AgentLanguage::Zig,
            AgentLanguage::Lua,
        ]
    }
}

pub(crate) fn agents_for_language(lang: AgentLanguage) -> Vec<AgentConfig> {
    match lang {
        AgentLanguage::Rust => vec![
            AgentConfig {
                kind: AgentKind::Format,
                name: String::new(),
                enabled: true,
                command: "cargo fmt".into(),
                trigger: AgentTrigger::AfterRun,
                timeout_secs: 30,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Lint,
                name: String::new(),
                enabled: true,
                command: "cargo clippy --message-format=json 2>&1".into(),
                trigger: AgentTrigger::AfterAgent(AgentKind::Format),
                timeout_secs: 120,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Build,
                name: String::new(),
                enabled: true,
                command: "cargo build --message-format=json 2>&1".into(),
                trigger: AgentTrigger::AfterAgent(AgentKind::Lint),
                timeout_secs: 120,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Test,
                name: String::new(),
                enabled: true,
                command: "cargo test 2>&1".into(),
                trigger: AgentTrigger::AfterAgent(AgentKind::Build),
                timeout_secs: 300,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Outdated,
                name: String::new(),
                enabled: true,
                command: "cargo outdated 2>&1".into(),
                trigger: AgentTrigger::Manual,
                timeout_secs: 120,
                working_dir: String::new(),
                before_run: String::new(),
            },
            audit_agent("cargo audit 2>&1"),
        ],
        AgentLanguage::TypeScript => vec![
            AgentConfig {
                kind: AgentKind::Format,
                name: String::new(),
                enabled: true,
                command: "npx prettier --write .".into(),
                trigger: AgentTrigger::AfterRun,
                timeout_secs: 30,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Lint,
                name: String::new(),
                enabled: true,
                command: "npx eslint . 2>&1".into(),
                trigger: AgentTrigger::AfterAgent(AgentKind::Format),
                timeout_secs: 120,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Build,
                name: String::new(),
                enabled: true,
                command: "npx tsc --noEmit 2>&1".into(),
                trigger: AgentTrigger::AfterAgent(AgentKind::Lint),
                timeout_secs: 120,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Test,
                name: String::new(),
                enabled: true,
                command: "npx jest 2>&1".into(),
                trigger: AgentTrigger::AfterAgent(AgentKind::Build),
                timeout_secs: 300,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Outdated,
                name: String::new(),
                enabled: true,
                command: "npm outdated 2>&1".into(),
                trigger: AgentTrigger::Manual,
                timeout_secs: 60,
                working_dir: String::new(),
                before_run: String::new(),
            },
            audit_agent("npm audit 2>&1"),
        ],
        AgentLanguage::Python => vec![
            AgentConfig {
                kind: AgentKind::Format,
                name: String::new(),
                enabled: true,
                command: "black .".into(),
                trigger: AgentTrigger::AfterRun,
                timeout_secs: 30,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Lint,
                name: String::new(),
                enabled: true,
                command: "ruff check . 2>&1".into(),
                trigger: AgentTrigger::AfterAgent(AgentKind::Format),
                timeout_secs: 120,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Build,
                name: String::new(),
                enabled: true,
                command: "python -m py_compile *.py 2>&1".into(),
                trigger: AgentTrigger::AfterAgent(AgentKind::Lint),
                timeout_secs: 60,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Test,
                name: String::new(),
                enabled: true,
                command: "pytest 2>&1".into(),
                trigger: AgentTrigger::AfterAgent(AgentKind::Build),
                timeout_secs: 300,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Outdated,
                name: String::new(),
                enabled: true,
                command: "pip list --outdated 2>&1".into(),
                trigger: AgentTrigger::Manual,
                timeout_secs: 60,
                working_dir: String::new(),
                before_run: String::new(),
            },
            audit_agent("pip-audit 2>&1"),
        ],
        AgentLanguage::Go => vec![
            AgentConfig {
                kind: AgentKind::Format,
                name: String::new(),
                enabled: true,
                command: "gofmt -w .".into(),
                trigger: AgentTrigger::AfterRun,
                timeout_secs: 30,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Lint,
                name: String::new(),
                enabled: true,
                command: "golangci-lint run 2>&1".into(),
                trigger: AgentTrigger::AfterAgent(AgentKind::Format),
                timeout_secs: 120,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Build,
                name: String::new(),
                enabled: true,
                command: "go build ./... 2>&1".into(),
                trigger: AgentTrigger::AfterAgent(AgentKind::Lint),
                timeout_secs: 120,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Test,
                name: String::new(),
                enabled: true,
                command: "go test ./... 2>&1".into(),
                trigger: AgentTrigger::AfterAgent(AgentKind::Build),
                timeout_secs: 300,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Outdated,
                name: String::new(),
                enabled: true,
                command: "go list -m -u all 2>&1".into(),
                trigger: AgentTrigger::Manual,
                timeout_secs: 60,
                working_dir: String::new(),
                before_run: String::new(),
            },
            audit_agent("govulncheck ./... 2>&1"),
        ],
        AgentLanguage::Java => vec![
            AgentConfig {
                kind: AgentKind::Format,
                name: String::new(),
                enabled: true,
                command: "./mvnw com.diffplug.spotless:spotless-maven-plugin:apply 2>&1".into(),
                trigger: AgentTrigger::AfterRun,
                timeout_secs: 60,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Lint,
                name: String::new(),
                enabled: true,
                command: "mvn checkstyle:check 2>&1".into(),
                trigger: AgentTrigger::AfterAgent(AgentKind::Format),
                timeout_secs: 120,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Build,
                name: String::new(),
                enabled: true,
                command: "mvn compile 2>&1".into(),
                trigger: AgentTrigger::AfterAgent(AgentKind::Lint),
                timeout_secs: 180,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Test,
                name: String::new(),
                enabled: true,
                command: "mvn test 2>&1".into(),
                trigger: AgentTrigger::AfterAgent(AgentKind::Build),
                timeout_secs: 300,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Outdated,
                name: String::new(),
                enabled: true,
                command: "mvn versions:display-dependency-updates 2>&1".into(),
                trigger: AgentTrigger::Manual,
                timeout_secs: 120,
                working_dir: String::new(),
                before_run: String::new(),
            },
            audit_agent("mvn org.owasp:dependency-check-maven:check 2>&1"),
        ],
        AgentLanguage::CSharp => vec![
            AgentConfig {
                kind: AgentKind::Format,
                name: String::new(),
                enabled: true,
                command: "dotnet format 2>&1".into(),
                trigger: AgentTrigger::AfterRun,
                timeout_secs: 60,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Lint,
                name: String::new(),
                enabled: true,
                command: "dotnet format --verify-no-changes 2>&1".into(),
                trigger: AgentTrigger::AfterAgent(AgentKind::Format),
                timeout_secs: 120,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Build,
                name: String::new(),
                enabled: true,
                command: "dotnet build 2>&1".into(),
                trigger: AgentTrigger::AfterAgent(AgentKind::Lint),
                timeout_secs: 180,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Test,
                name: String::new(),
                enabled: true,
                command: "dotnet test 2>&1".into(),
                trigger: AgentTrigger::AfterAgent(AgentKind::Build),
                timeout_secs: 300,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Outdated,
                name: String::new(),
                enabled: true,
                command: "dotnet list package --outdated 2>&1".into(),
                trigger: AgentTrigger::Manual,
                timeout_secs: 60,
                working_dir: String::new(),
                before_run: String::new(),
            },
            audit_agent("dotnet list package --vulnerable 2>&1"),
        ],
        AgentLanguage::Ruby => vec![
            AgentConfig {
                kind: AgentKind::Format,
                name: String::new(),
                enabled: true,
                command: "bundle exec rubocop -a 2>&1".into(),
                trigger: AgentTrigger::AfterRun,
                timeout_secs: 60,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Lint,
                name: String::new(),
                enabled: true,
                command: "bundle exec rubocop 2>&1".into(),
                trigger: AgentTrigger::AfterAgent(AgentKind::Format),
                timeout_secs: 120,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Build,
                name: String::new(),
                enabled: true,
                command: "ruby -c **/*.rb 2>&1".into(),
                trigger: AgentTrigger::AfterAgent(AgentKind::Lint),
                timeout_secs: 60,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Test,
                name: String::new(),
                enabled: true,
                command: "bundle exec rspec 2>&1".into(),
                trigger: AgentTrigger::AfterAgent(AgentKind::Build),
                timeout_secs: 300,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Outdated,
                name: String::new(),
                enabled: true,
                command: "bundle outdated 2>&1".into(),
                trigger: AgentTrigger::Manual,
                timeout_secs: 60,
                working_dir: String::new(),
                before_run: String::new(),
            },
            audit_agent("bundle audit check 2>&1"),
        ],
        AgentLanguage::Swift => vec![
            AgentConfig {
                kind: AgentKind::Format,
                name: String::new(),
                enabled: true,
                command: "swift-format format -i -r . 2>&1".into(),
                trigger: AgentTrigger::AfterRun,
                timeout_secs: 30,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Lint,
                name: String::new(),
                enabled: true,
                command: "swiftlint 2>&1".into(),
                trigger: AgentTrigger::AfterAgent(AgentKind::Format),
                timeout_secs: 120,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Build,
                name: String::new(),
                enabled: true,
                command: "swift build 2>&1".into(),
                trigger: AgentTrigger::AfterAgent(AgentKind::Lint),
                timeout_secs: 180,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Test,
                name: String::new(),
                enabled: true,
                command: "swift test 2>&1".into(),
                trigger: AgentTrigger::AfterAgent(AgentKind::Build),
                timeout_secs: 300,
                working_dir: String::new(),
                before_run: String::new(),
            },
        ],
        AgentLanguage::Kotlin => vec![
            AgentConfig {
                kind: AgentKind::Format,
                name: String::new(),
                enabled: true,
                command: "ktlint --format 2>&1".into(),
                trigger: AgentTrigger::AfterRun,
                timeout_secs: 60,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Lint,
                name: String::new(),
                enabled: true,
                command: "ktlint 2>&1".into(),
                trigger: AgentTrigger::AfterAgent(AgentKind::Format),
                timeout_secs: 120,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Build,
                name: String::new(),
                enabled: true,
                command: "./gradlew compileKotlin 2>&1".into(),
                trigger: AgentTrigger::AfterAgent(AgentKind::Lint),
                timeout_secs: 180,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Test,
                name: String::new(),
                enabled: true,
                command: "./gradlew test 2>&1".into(),
                trigger: AgentTrigger::AfterAgent(AgentKind::Build),
                timeout_secs: 300,
                working_dir: String::new(),
                before_run: String::new(),
            },
        ],
        AgentLanguage::Cpp => vec![
            AgentConfig {
                kind: AgentKind::Format,
                name: String::new(),
                enabled: true,
                command: "find . -name '*.cpp' -o -name '*.h' | xargs clang-format -i".into(),
                trigger: AgentTrigger::AfterRun,
                timeout_secs: 30,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Lint,
                name: String::new(),
                enabled: true,
                command: "cppcheck --enable=all . 2>&1".into(),
                trigger: AgentTrigger::AfterAgent(AgentKind::Format),
                timeout_secs: 120,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Build,
                name: String::new(),
                enabled: true,
                command: "cmake --build build 2>&1".into(),
                trigger: AgentTrigger::AfterAgent(AgentKind::Lint),
                timeout_secs: 180,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Test,
                name: String::new(),
                enabled: true,
                command: "ctest --test-dir build 2>&1".into(),
                trigger: AgentTrigger::AfterAgent(AgentKind::Build),
                timeout_secs: 300,
                working_dir: String::new(),
                before_run: String::new(),
            },
        ],
        AgentLanguage::Elixir => vec![
            AgentConfig {
                kind: AgentKind::Format,
                name: String::new(),
                enabled: true,
                command: "mix format".into(),
                trigger: AgentTrigger::AfterRun,
                timeout_secs: 30,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Lint,
                name: String::new(),
                enabled: true,
                command: "mix credo 2>&1".into(),
                trigger: AgentTrigger::AfterAgent(AgentKind::Format),
                timeout_secs: 120,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Build,
                name: String::new(),
                enabled: true,
                command: "mix compile 2>&1".into(),
                trigger: AgentTrigger::AfterAgent(AgentKind::Lint),
                timeout_secs: 120,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Test,
                name: String::new(),
                enabled: true,
                command: "mix test 2>&1".into(),
                trigger: AgentTrigger::AfterAgent(AgentKind::Build),
                timeout_secs: 300,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Outdated,
                name: String::new(),
                enabled: true,
                command: "mix hex.outdated 2>&1".into(),
                trigger: AgentTrigger::Manual,
                timeout_secs: 60,
                working_dir: String::new(),
                before_run: String::new(),
            },
            audit_agent("mix hex.audit 2>&1"),
        ],
        AgentLanguage::Zig => vec![
            AgentConfig {
                kind: AgentKind::Format,
                name: String::new(),
                enabled: true,
                command: "zig fmt .".into(),
                trigger: AgentTrigger::AfterRun,
                timeout_secs: 30,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Lint,
                name: String::new(),
                enabled: true,
                command: "zig build 2>&1".into(),
                trigger: AgentTrigger::AfterAgent(AgentKind::Format),
                timeout_secs: 120,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Build,
                name: String::new(),
                enabled: true,
                command: "zig build 2>&1".into(),
                trigger: AgentTrigger::AfterAgent(AgentKind::Lint),
                timeout_secs: 120,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Test,
                name: String::new(),
                enabled: true,
                command: "zig build test 2>&1".into(),
                trigger: AgentTrigger::AfterAgent(AgentKind::Build),
                timeout_secs: 300,
                working_dir: String::new(),
                before_run: String::new(),
            },
        ],
        AgentLanguage::Lua => vec![
            AgentConfig {
                kind: AgentKind::Format,
                name: String::new(),
                enabled: true,
                command: "stylua .".into(),
                trigger: AgentTrigger::AfterRun,
                timeout_secs: 30,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Lint,
                name: String::new(),
                enabled: true,
                command: "luacheck . 2>&1".into(),
                trigger: AgentTrigger::AfterAgent(AgentKind::Format),
                timeout_secs: 120,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Build,
                name: String::new(),
                enabled: true,
                command: "luac -p *.lua 2>&1".into(),
                trigger: AgentTrigger::AfterAgent(AgentKind::Lint),
                timeout_secs: 60,
                working_dir: String::new(),
                before_run: String::new(),
            },
            AgentConfig {
                kind: AgentKind::Test,
                name: String::new(),
                enabled: true,
                command: "busted 2>&1".into(),
                trigger: AgentTrigger::AfterAgent(AgentKind::Build),
                timeout_secs: 300,
                working_dir: String::new(),
                before_run: String::new(),
            },
        ],
    }
}
